# **Numpy**

In [2]:
import numpy as np

Essa lista contém questões práticas incluindo os seguintes tópicos com numpy.

* Criação de array e seus atributos, intervalos numéricos em numPy
* Slicing e indexação de NumPy Array.
* Manipulação, pesquisa, classificação e divisão de arrays.
* Funções matemáticas com arrays e broadcasting arrays NumPy. 

## **Crie um array inteiro 4x2 e mostre seus atributos**

Os elementos deven ser um tipo de int16 sem sinal. E imprima os seguintes atributos: formato do array; dimensões; comprimento de cada elemento do array.

In [ ]:
#########################################
#         Escreva o código aqui
#########################################

##### Resultado esperado:
<pre>
Mostrando Array
[[64392 31655]
 [32579     0]
 [49248   462]
 [    0     0]]

Mostrando Attributos:

Formato do array:  (4, 2)
Número de dimensões:  2
Comprimento de cada elemento do array:  2
</pre>

## **Crie uma array de inteiros 5X2 com um intervalo entre 100 e 200, de modo que a diferença entre cada elemento seja 10**

In [ ]:
#########################################
#         Escreva o código aqui
#########################################

##### Resultado esperado:
<pre>
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]
</pre>

## **Baseado no array fornecido. Retorne um array de itens com a terceira coluna de todas as linhas**

In [ ]:
array_00 = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

In [ ]:
#########################################
#         Escreva o código aqui
#########################################

##### Resultado esperado:
<pre>
Mostrando array de entrada
[[11 22 33]
 [44 55 66]
 [77 88 99]]

Novo array com a terceira coluna de cada linha
[33 66 99]
</pre>

## **Retorne um array com os valores presentes nas linhas ímpares com colunas pares baseado no seguinte array**

In [1]:
array_01 = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

NameError: ignored

In [ ]:
#########################################
#         Escreva o código aqui
#########################################

##### Resultado esperado:
<pre>
Mostrando array de entrada
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

Array resultante (linha ímpar x coluna par)
[[ 6 12]
 [30 36]
 [54 60]]
</pre>

## **Crie um array de resultado somando os seguintes arrays. Em seguida, modifique o array resultante calculando o quadrado de cada elemento**

In [ ]:
array_02 = np.array([[5, 6, 9], [21 ,18, 27]])
array_03 = np.array([[15 ,33, 24], [4 ,7, 1]])

In [ ]:
#########################################
#         Escreva o código aqui
#########################################

##### Resultado esperado:
<pre>
A soma dos arrays é: 
[[20 39 33]
 [25 25 28]]

Resultado depois de calcular o quadrado de cada número:
[[ 400 1521 1089]
 [ 625  625  784]]
</pre>

## **Faça a soma, subtração, multiplicação e divisão dos arrays**

In [ ]:
array_04 = np.array([1, 2, 3])
array_05 = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
#########################################
#         Escreva o código aqui
#########################################

##### Resultado esperado:
<pre>
Soma: 
[[2 4 6]
 [5 7 9]]
Subtração: 
[[ 0  0  0]
 [-3 -3 -3]]
Multiplicação: 
[[ 1  4  9]
 [ 4 10 18]]
divisão: 
[[1.   1.   1.  ]
 [0.25 0.4  0.5 ]]
</pre>

## **Divida o array em quatro sub-arrays de tamanhos iguais**

Crie um array de inteiros 8X3 com um intervalo entre 10 e 34 de modo que a diferença entre cada elemento seja 1 e, em seguida, faça a subdivisão. 

In [ ]:
#########################################
#         Escreva o código aqui
#########################################

##### Resultado esperado:
<pre>
Criando o array de 8X3 usando numpy.arange
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividindo o array em 4 sub-arrays

[array([[10, 11, 12],[13, 14, 15]]), 
array([[16, 17, 18],[19, 20, 21]]), 
array([[22, 23, 24],[25, 26, 27]]), 
array([[28, 29, 30],[31, 32, 33]])]
</pre>

## **Ordenar o seguinte array da seguinte forma:**

* Oredene pela segunda linha
* Ordene pela terceira coluna

In [ ]:
import numpy as np
array_06 = np.array([[34,43,73],[82,22,12],[53,94,66]])

In [ ]:
array_06

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

[[73 43 34]
 [12 22 82]
 [66 94 53]]
[[82 22 12]
 [53 94 66]
 [34 43 73]]


##### Resultado esperado:
<pre>
Mostrando o array original
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Ordenando o array pela segunda linha
[[73 43 34]
 [12 22 82]
 [66 94 53]]

Ordenando o array pela terceira coluna
[[82 22 12]
 [34 43 73]
 [53 94 66]]
</pre>

## **Imprima o máx. do eixo 0 e mín. Do eixo 1 do seguinte array**

In [ ]:
array_07 = np.array([[34,43,73],[82,22,12],[53,94,66]])

In [ ]:
#########################################
#         Escreva o código aqui
#########################################

##### Resultado esperado:
<pre>
Mostrando array original
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Mostando amin do eixo 1
[34 12 53]

Mostrando amax do eixo 0
[82 94 73]
</pre>

## **Exclua a segunda coluna de um determinado array e insira a nova coluna seguinte em seu lugar**

In [ ]:
array_08    = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
nova_coluna = np.array([[10,10,10]])

In [ ]:
#########################################
#         Escreva o código aqui
#########################################

##### Resultado esperado:
<pre>
Mostrando array original
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Array depois de deletar a segunda coluna
[[34 73]
 [82 12]
 [53 66]]

Array depois de inserir a nova coluna no lugar da coluna excluída
[[34 10 73]
 [82 10 12]
 [53 10 66]]
</pre>